dist: xenial
language: go
go:
  - 1.14.1
env:
  - REALESE_BRANCHES="release-v[0-9]+\.[0-9]+\.x" RELEASE_TAGS="v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?" BUILD_OS="(linux $([ $TRAVIS_EVENT_TYPE == cron ] || [[ $TRAVIS_BRANCH =~ $RELEASE_BRANCHES ]] || [[ $TRAVIS_TAG =~ $RELEASE_TAGS ]] && echo darwin))" BUILD_ARCH=amd64 GATE_API_BRANCH=release-1.20.x
services:
  - docker

before_script:
  - docker pull openjdk:11.0.3-stretch
  - docker run -u root -w /workspace -v `pwd`:/workspace --entrypoint /workspace/.travisci/generate_swagger.sh --rm openjdk:11.0.3-stretch release-1.20.x 
    
script:
  - docker pull golang:1.14.1-stretch
  - env; for o in $BUILD_OS; do for a in $BUILD_ARCH; do docker run -u root -w /go/src/github.com/codilime/floodgate -v `pwd`:/go/src/github.com/codilime/floodgate --entrypoint /go/src/github.com/codilime/floodgate/.travisci/build.sh --rm golang:1.14.1-stretch -g $GATE_API_BRANCH -o $o -1 $a; sudo mv floodgate floodgate-$g.$o.$a ; done; done
  - sudo chown $SUDO_USER:$SUDO_USER -R .

after_success:
  - .travisci/start_spinnaker.sh $GATE_API_BRANCH

