package spinnakerresource

import (
	"encoding/json"
	"reflect"

	jd "github.com/josephburnett/jd/lib"

	"github.com/codilime/floodgate/gateclient"
)

// Resource is basic struct for all spinnaker resources
type Resource struct {
	localState, remoteState []byte
}

// IsChanged is used to compare local and remmote state
func (r Resource) IsChanged() (bool, error) {
	localJSON, remoteJSON, err := r.unmarshalStates()
	if err != nil {
		return false, err
	}

	for k := range localJSON {
		if _, exists := remoteJSON[k]; !exists {
			return true, nil
		}
		if !reflect.DeepEqual(localJSON[k], remoteJSON[k]) {
			return true, nil
		}
	}

	return false, nil
}

// GetLocalState returns local state of an object.
func (r Resource) GetLocalState() ([]byte, error) {
	return r.localState, nil
}

// GetFullDiff function returns diff against remote state
func (r Resource) GetFullDiff() string {
	a, _ := jd.ReadJsonString(string(r.remoteState))
	b, _ := jd.ReadJsonString(string(r.localState))

	return a.Diff(b).Render()
}

func (r Resource) getNormalizedRemoteState() ([]byte, error) {
	localJSON, remoteJSON, err := r.unmarshalStates()
	if err != nil {
		return []byte("{}"), err
	}

	remoteJSONNormalized := make(map[string]interface{})
	for k := range localJSON {
		if key, exists := remoteJSON[k]; exists {
			remoteJSONNormalized[k] = key
		}
	}

	remoteJSONNormalizedByte, err := json.Marshal(remoteJSONNormalized)
	if err != nil {
		return []byte("{}"), err
	}

	return remoteJSONNormalizedByte, nil
}

// GetNormalizedDiff function returns diff on only managed resources
func (r Resource) GetNormalizedDiff() string {
	remoteState, _ := r.getNormalizedRemoteState()
	a, _ := jd.ReadJsonString(string(remoteState))
	b, _ := jd.ReadJsonString(string(r.localState))

	return a.Diff(b).Render()
}

// GetRemoteState is used to view stored remote state.
func (r Resource) GetRemoteState() []byte {
	return r.remoteState
}

func (r *Resource) unmarshalStates() (localJSON, remoteJSON map[string]interface{}, err error) {
	if err = json.Unmarshal(r.localState, &localJSON); err != nil {
		return
	}

	if err = json.Unmarshal(r.remoteState, &remoteJSON); err != nil {
		return
	}

	var state []byte

	if localJSON, state, err = r.deleteAutogenFields(localJSON); err != nil {
		return
	}
	r.localState = state

	if remoteJSON, state, err = r.deleteAutogenFields(remoteJSON); err != nil {
		return
	}
	r.remoteState = state

	return
}

// deleteAutogenFields is used to delete autogenerated fields from given state
func (r *Resource) deleteAutogenFields(stateJSON map[string]interface{}) (map[string]interface{}, []byte, error) {
	autogeneratedFields := []string{"lastModifiedBy", "updateTs", "createTs", "index"}

	for _, field := range autogeneratedFields {
		delete(stateJSON, field)
	}

	state, err := json.Marshal(stateJSON)
	if err != nil {
		return nil, nil, err
	}

	return stateJSON, state, nil
}

// Resourcer interface for Spinnaker resource
type Resourcer interface {
	// Init is used configure object and to load remote data into it
	Init(api *gateclient.GateapiClient, localData map[string]interface{}) error
	// IsChanged is used to compare local and remmote state
	IsChanged() (bool, error)
	// LocalState get resource's local state
	LocalState() []byte
	// RemoteState get resource's remote state
	RemoteState() []byte
	// LoadRemoteState load resource's remote state from Spinnaker
	LoadRemoteState(spinnakerAPI *gateclient.GateapiClient) error
	// LoadRemoteStateByName load resource's remote state from Spinnaker by provided name
	LoadRemoteStateByName(spinnakerAPI *gateclient.GateapiClient, name string) error
	// SaveLocalState save resource's local state to Spinnaker
	SaveLocalState(spinnakerAPI *gateclient.GateapiClient) error
}
