endpoint: http://spinnaker/api/v1
auth:
  basic:
    enabled: true
    user: admin
    password: GATE_PASS
libraries:
  - /floodgate/libs/sponnet
resources:
  - /floodgate/resources/examples/resources/applications
  - /floodgate/resources/examples/resources/pipelines
  - /floodgate/resources/examples/resources/pipelinetemplates

